name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
                python-version: 3.8 

      - name: Install pip dependencies
        run: |
                python -m pip install --upgrade pip
                pip install build twine

      - name: Build a binary wheel and a source tarball
        run: |
                python -m build --sdist --wheel --outdir dist/
                twine check dist/*

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
